# Generated by Django 6.0.5 on 2026-05-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo de Análisis',
                'verbose_name_plural': 'Archivos de Análisis',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.IntegerField()),
                ('texto', models.TextField()),
                ('clasificacion', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutro', 'Neutro')], max_length=10)),
                ('puntaje_polaridad', models.FloatField()),
                ('libreria_usada', models.CharField(max_length=30)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='sentiminer.archivoanalisis')),
            ],
            options={
                'verbose_name': 'Resultado por Línea',
                'verbose_name_plural': 'Resultados por Línea',
                'ordering': ['numero_linea'],
            },
        ),
        migrations.CreateModel(
            name='ResumenAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lineas', models.IntegerField()),
                ('positivas', models.IntegerField()),
                ('negativas', models.IntegerField()),
                ('neutras', models.IntegerField()),
                ('porcentaje_positivo', models.FloatField()),
                ('porcentaje_negativo', models.FloatField()),
                ('porcentaje_neutro', models.FloatField()),
                ('sentimiento_predominante', models.CharField(max_length=10)),
                ('archivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen', to='sentiminer.archivoanalisis')),
            ],
            options={
                'verbose_name': 'Resumen de Análisis',
                'verbose_name_plural': 'Resúmenes de Análisis',
            },
        ),
    ]
